#!/usr/bin/env python3
"""Build the Estonian and English pages from one template.

    python3 tools/build_i18n.py          # rewrite index.html and en/index.html
    python3 tools/build_i18n.py --check  # exit 1 if either file is out of date

index.html is both the template and the Estonian page (served at /), and
en/index.html is the English page (served at /en/). All translatable text
lives in TRANSLATIONS in script.js; elements opt in with attributes:

    data-i18n="key"                  element text (element must hold text only)
    data-i18n-alt="key"              alt
    data-i18n-aria="key"             aria-label
    data-i18n-content="key"          content (meta tags)
    data-i18n-href="key"             href
    data-i18n-hreflang="key"         hreflang
    data-i18n-lang="key"             lang

Blocks between <!-- i18n:et-only --> and <!-- /i18n:et-only --> are left out
of the English page. Uses only the Python standard library.
"""
import html
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PAGES = {"et": ROOT / "index.html", "en": ROOT / "en" / "index.html"}
ATTRS = {
    "alt": "alt",
    "aria": "aria-label",
    "content": "content",
    "href": "href",
    "hreflang": "hreflang",
    "lang": "lang",
}
GENERATED_NOTE = (
    "<!-- Generated by tools/build_i18n.py from index.html + script.js. "
    "Edit those, then rerun the script. -->\n"
)


def load_translations():
    js = (ROOT / "script.js").read_text(encoding="utf-8")
    match = re.search(r"var TRANSLATIONS = (\{.*?\n\});", js, re.S)
    if not match:
        sys.exit("TRANSLATIONS object not found in script.js")
    # The object is JSON apart from bare et/en keys and trailing commas.
    source = re.sub(r"(\{|,)\s*(et|en):", r'\1 "\2":', match.group(1))
    source = re.sub(r",(\s*[}\]])", r"\1", source)
    return json.loads(source)


def translate(template, lang, translations):
    missing = set()

    def value(key):
        entry = translations.get(key)
        if entry is None or lang not in entry:
            missing.add(key)
            return None
        return entry[lang]

    def replace_text(m):
        tag, attrs, key, inner = m.group(1), m.group(2), m.group(3), m.group(4)
        if "<" in inner:
            sys.exit(f'data-i18n="{key}" must be on an element that holds only text')
        text = value(key)
        if text is None:
            return m.group(0)
        return f"<{tag}{attrs}>{html.escape(text, quote=False)}</{tag}>"

    def replace_attrs(m):
        tag = m.group(0)
        for suffix, attr in ATTRS.items():
            key_match = re.search(rf'\sdata-i18n-{suffix}="([^"]+)"', tag)
            if not key_match:
                continue
            text = value(key_match.group(1))
            if text is None:
                continue
            pattern = rf'(?<=\s){re.escape(attr)}="[^"]*"'
            if not re.search(pattern, tag):
                sys.exit(f"{tag[:80]}... has data-i18n-{suffix} but no {attr} attribute")
            new = f'{attr}="{html.escape(text, quote=True)}"'
            tag = re.sub(pattern, lambda _: new, tag, count=1)
        return tag

    out = re.sub(
        r'<(\w+)(\s[^>]*?data-i18n="([^"]+)"[^>]*)>(.*?)</\1>',
        replace_text,
        template,
        flags=re.S,
    )
    out = re.sub(r"<\w+\s[^>]*\sdata-i18n-[^>]*>", replace_attrs, out)

    if lang != "et":
        out = re.sub(
            r"[ \t]*<!-- i18n:et-only -->.*?<!-- /i18n:et-only -->\n?", "", out, flags=re.S
        )
        out = out.replace("<!DOCTYPE html>\n", "<!DOCTYPE html>\n" + GENERATED_NOTE, 1)
    return out, missing


def main():
    check = "--check" in sys.argv[1:]
    translations = load_translations()
    template = PAGES["et"].read_text(encoding="utf-8")

    stale = []
    for lang, path in PAGES.items():
        out, missing = translate(template, lang, translations)
        if missing:
            sys.exit(f"Missing '{lang}' translations in script.js: {', '.join(sorted(missing))}")
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if out != current:
            stale.append(str(path.relative_to(ROOT)))
            if not check:
                path.parent.mkdir(exist_ok=True)
                path.write_text(out, encoding="utf-8")

    if check and stale:
        sys.exit("Out of date, run `python3 tools/build_i18n.py`: " + ", ".join(stale))
    print(("Updated: " + ", ".join(stale)) if stale else "Pages are up to date.")


if __name__ == "__main__":
    main()
